# Where you get the Checkout action -> https://github.com/marketplace/actions/checkout

name: practice_github

on: push

jobs:
  practice_level_1:
    runs-on: ubuntu-latest
    steps:
    
    - name: Github Checkout
      uses: actions/checkout@v4

    - name: Welcome Message
      run:  |
            echo "Hello World"
            ls -ltr

    - name: Github Action Context
      run: echo "Hello ${{toJson(github)}}"