# # This is a basic workflow that is manually triggered
# name: Manual workflow

# # Controls when the action will run. Workflow runs when manually triggered using the UI
# # or API.
# on: [workflow_dispatch, push]

# jobs:
#   # This workflow contains a single job called "greet"
#   greet:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Send greeting
      # run: echo "Hello ${{ github.event.inputs.name }}"
#     - name: Github Action Context
      # run: echo "${{toJson(github)}}"

name: practice_github

on: push

jobs:
  practice_level_1:
    runs-on: ubuntu-latest
    steps:
    - name: Welcome Message
      run:  echo "Hello World"